### PR TITLE
Fixing CSS bugs and making the blockquotes more usable

### PR DESCRIPTION
**Pull request by jonas-sk**
This pull request primarily fixes some bugs with the ordered lists and the `mhn` negative margin classes. It additionally redesigns the blockquotes to become more readable (black text, smaller font size) and uses `object-fit: cover` for the `media-block` partials, so all images have the same size.

### CODE REVIEW

**Comment by erquhart** [comment]
Pull quotes usually repeat inline content, weird that we're styling inline content _as_ pull quotes. Anyway, awesome improvements! I do think the styling of the quote text itself should be distinct, maybe just a tad stronger font weight?

**Comment by jonas-sk** [comment]
Thank you for the feedback! I think this depends on what role you accord the quotes. Normally, my understanding (coming from an academic & markdown background) is that blockquotes serve as an integral part of the text where a quote exceeds (normally) 40 words. With this project they're more like "pull-out" quotes akin to what some printed newspapers do, which - as you said - repeat the text. I think we should either decide on one or separate the two. I'll first look into making the blockquotes more distinct

**Comment by jonas-sk** [comment]
Regarding changing the font-weight for the blockquotes. Because the font doesn't support smaller increments than 100, even a increase by 10 in font weight will look like this:

grafik

I personally prefer the normal font weight then but it's up to you

**Comment by erquhart** [comment]
I don't know, I think looks fantastic, honestly. The text should stand out more in those blockquotes and this does the trick.

**Pull request closed without merging**
