### PR TITLE
removes unneeded force href after login

### PR DESCRIPTION
**Pull request by bdougie**
See issue #1

### CODE REVIEW

**Comment by erquhart** [comment]
@bdougie I believe removing this leaves us without a redirect after login, so they log in and then just get this gray screen. This was a quick fix, we should probably improve moving forward.

For the moment, maybe we should just check for the `admin` segment in the url as well.

**Comment by Benaiah** [comment]
@bdougie @erquhart if I'm understanding the issue correctly, it should just need `&& window.location.pathname.startsWith('/admin/')` or an equivalent in the conditional - does that make sense or am I missing something?

**Comment by bdougie** [comment]
Yes based on @erquhart's suggestion, that seems like it would work. I have added the cms/identity/git-gateway to a project to test noticing there is no redirect after confirmation. Wonder if that is related or not. Trying to triage on my end

**Comment by erquhart** [comment]
@bdougie still seeing this issue?

**Comment by bdougie** [comment]
I believe this is fixed and be closed.

**Pull request closed without merging**
